FROM python:3.11

WORKDIR /db_init

# Установка psycopg2
RUN pip install psycopg2 faker

# Копирование вашего скрипта и выполнение
COPY seed_db.py /db_init/seed_db.py
CMD ["python", "/db_init/seed_db.py"]
