CREATE TABLE courses (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        course_code VARCHAR(255),
                        credits INTEGER,
                        lecturer VARCHAR(255),
                        name VARCHAR(255)
);

CREATE TABLE students (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          enrollment_year INTEGER,
                          full_name VARCHAR(255),
                          student_id VARCHAR(255)
);

CREATE TABLE enrollments (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            enrollment_date TIMESTAMP(6),
                            status VARCHAR(255),
                            course_id BIGINT,
                            student_id BIGINT
);
